# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JdCSRg_f07gsG5zOxVrqm9nIjhT55XE
"""

import pandas as pd
baza={
    "FISH":[ "Pozilov Abdulaziz" , "Topivoldiyev Abbosbek" , "Sobirov ALi","Xolmatov Yaxyo","Jalilov Vali","Sobirjonova Malika ","Ro'zmatova Ruxshona ","Odilova Hilola","Azizbekov Jasurbek","Mahmudov Asilbek",],
    "Yosh":[ "19" , "19" ,"19" ,"32" ,"48" ,"56" ,"21" ,"16" ,"17" ,"15" ,  ],
    "Maktabi":[ '17-maktab', '28-maktab','23-maktab','22-maktab','30-maktab','52-maktab','127-maktab','115-maktab','27-maktab','18-maktab',],
    "jinsi":[ 'erkak', 'erkak','erkak','erkak','erkak','ayol','ayol','ayol','erkak','erkak',] ,
    "Manzili":[  "Xo'jaobod tumani" ,"Farg'ona tumani" ,"Toshloq tumani" ,"Bog'dod tumani" ,"Quva tumani" ,"Farg'ona tumani" ,"Farg'ona tumani" ,"Xo'jaobod tumani" ,"Dasht tumani" ,"Kenegas tumani" ,],
}
malumot=pd.DataFrame(baza)
print(malumot)

filtr=malumot[(malumot['jinsi']=='ayol') & (malumot['Yosh']>'15') ]
print(filtr)

filtr=malumot[(malumot['jinsi']=='ayol') & (malumot['Yosh']>'15') & (malumot['Manzili']=="Farg'ona tumani")]
print(filtr)